### ISSUE TITLE
Data Cleaning and Wrangling

### ISSUE THREAD

**Issue by alberto-martino** [leomassoc/LSE-DS105L-Data-Detectives#2]
**Deadline:** Friday 24 march

## Context

What motivated the creation of this issue?

## Tasks

To-Do:
- [x] Import data using API (@leomassoc) 
- [x] Merging Process (@amartino1-lse) on the County and State-Level
- [x] Eventually scrape the website https://www.univstats.com/states/
- [x] Look at the number of education establishments per county and compare it to GDP per capita

**Comment by alberto-martino** [comment]
### Notebook 4 Uploaded.

The notebook contains all the details on education and salary available. @SEYIOJOLSE and @atelemtayeva will proceed with the 
**data visualisation** of the data frame provided and called `merged_census`.

⏰ **Deadline** Saturday 25 March 6 PM - To leave enough time to prepare the presentation for Monday.
