### ISSUE TITLE
Update ReadME 

### ISSUE THREAD

**Issue by alberto-martino** [leomassoc/LSE-DS105L-Data-Detectives#4]
**Deadline:** 15 april

## Context

To give a clear overview of our project. We may take inspiration from our first presentation.

## Tasks

- [x] Remove all template text
- [x] Insert a context section
- [x] Create an index of our project
- [x] Update Team and Roles
